AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda layer to execute Selenium on headless chromium

Metadata:
  AWS::ServerlessRepo::Application:
    Name: aws-lambda-layer-selenium-headless-chromium
    Description: Lambda layer to execute Selenium on headless chromium
    Author: judneer
    SpdxLicenseId: MIT-0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['layer', 'lambda', 'python', 'selenium']
    HomePageUrl: https://github.com/aws-samples/aws-lambda-layer-selenium-headless-chromium
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/aws-samples/aws-lambda-layer-selenium-headless-chromium

Resources:
  SeleniumHeadlessChromium:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
      ContentUri: layer
      Description: Lambda layer to execute Selenium on headless chromium
      LayerName: selenium-headless-chromium-python36
      LicenseInfo: MIT-0
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile

Outputs:
  LayerArn:
    Value: !Ref SeleniumHeadlessChromium
